[app]
title = DistanceTrainer
package.name = distancetrainer
package.domain = org.test
source.dir = .
source.include_exts = py,kv,png,jpg,ttf,atlas
version = 0.1
requirements = python3,kivy
orientation = portrait
fullscreen = 0
android.api = 31
android.minapi = 21
android.ndk = 23b
android.private_storage = 1
android.permissions = INTERNET
android.archs = armeabi-v7a, arm64-v8a
android.allow_backup = 1
android.build_tools_version = 30.0.3
android.add_javac_opts = -encoding UTF-8
